WITH CAR AS
(SELECT CAR_ID
 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
 GROUP BY CAR_ID
)
SELECT CAR_ID,
    CASE WHEN B.CAR_ID IN (SELECT CAR_ID FROM CAR) THEN '대여중'
        ELSE '대여 가능'
        END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
GROUP BY B.CAR_ID
ORDER BY B.CAR_ID DESC