-- 코드를 입력하세요
WITH RECURSIVE CTE AS 
(
    SELECT 0 AS NUM
    UNION ALL
    SELECT NUM + 1 
    FROM CTE
    WHERE NUM < 23
)
SELECT C.NUM HOUR, COUNT(HOUR(A.DATETIME)) 'COUNT'
FROM ANIMAL_OUTS A
    RIGHT JOIN CTE C
ON HOUR(A.DATETIME) = C.NUM
GROUP BY C.NUM
ORDER BY C.NUM