WITH MAX_RESULT AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR
),
ECOLI_YEAR_DATA AS (
    SELECT ID, 
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX_SIZE - SIZE_OF_COLONY AS YEAR_DEV 
    FROM ECOLI_DATA
    JOIN MAX_RESULT MR
    ON YEAR(DIFFERENTIATION_DATE) = MR.YEAR
)
SELECT YEAR, YEAR_DEV, ID
FROM ECOLI_YEAR_DATA
ORDER BY YEAR, YEAR_DEV